-- inserts payload
INSERT INTO AerospaceSector.Payload VALUES (1,"Starlink 2 v1.0", 14500, false);
INSERT INTO AerospaceSector.Payload VALUES (2,"ISS supplies CRS-20", 1.997, false);
INSERT INTO AerospaceSector.Payload VALUES (3,"Crew Dragon", 12530, true);
INSERT INTO AerospaceSector.Payload VALUES (4,"NROL-108", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (5, "Crew-2", 13000, true);
INSERT INTO AerospaceSector.Payload VALUES (6,"Starlink 2 v1.0 & Capella-6 & tyvak-0130", 14000, false);
INSERT INTO AerospaceSector.Payload VALUES (7,"Sxm-8", 7000, false);
INSERT INTO AerospaceSector.Payload VALUES (8,"GPS III-05", 4331, false);
INSERT INTO AerospaceSector.Payload VALUES (9,"Starlink Group 2-1 (v1.5)", 13260, false);
INSERT INTO AerospaceSector.Payload VALUES (10,"Inspiration 4", 12519, true);
INSERT INTO AerospaceSector.Payload VALUES (11,"Türksat 5B", 4500, false);
INSERT INTO AerospaceSector.Payload VALUES (12,"Shepherd demo & LDPE-2", 44500, false);
INSERT INTO AerospaceSector.Payload VALUES (13,"Danuri (korea pathfinder Lunar Orbiter", 679, false);
INSERT INTO AerospaceSector.Payload VALUES (14,"Crew-5", 13000, true);
INSERT INTO AerospaceSector.Payload VALUES (15,"Starlink Group 4-36", 16700, false);
INSERT INTO AerospaceSector.Payload VALUES (16,"Starlink Group 5-5", 15000, false);
INSERT INTO AerospaceSector.Payload VALUES (17,"Transport and layer tracking", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (18, "Starlink 6-2", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (19,"Intelsat 40e TEMPO", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (20,"ViaSat-3 Americas & Aurora 4A & Nusantara", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (21,"Transporter-7", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (22,"None", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (23,"Yowgen 34C", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (24,"Crew", NULL, true);
INSERT INTO AerospaceSector.Payload VALUES (25,"Moon recon experiments", 12300, false);
INSERT INTO AerospaceSector.Payload VALUES (26,"KH-11 kennen 18A", 12300, false);
INSERT INTO AerospaceSector.Payload VALUES (27,"KH-11 kennen 18B", 12300, false);
INSERT INTO AerospaceSector.Payload VALUES (28,"Orion 10", 7000, false);
INSERT INTO AerospaceSector.Payload VALUES (29,"USA-275", 14000, false);
INSERT INTO AerospaceSector.Payload VALUES (30,"2 SAR satellites", 4000, false);
INSERT INTO AerospaceSector.Payload VALUES (31,"3 HawkEye 360 satellites", 7000, false);
INSERT INTO AerospaceSector.Payload VALUES (32,"Science Research satellite", 3000, false);
INSERT INTO AerospaceSector.Payload VALUES (33,"2 blackeye GEN-2 satellites", 2354, false);
INSERT INTO AerospaceSector.Payload VALUES (34,"18 experiments", 3327, false);
INSERT INTO AerospaceSector.Payload VALUES (35,"USSF satellite", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (36,"Weather analysis satellite", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (37,"1 pilot", NULL, false);
INSERT INTO AerospaceSector.Payload VALUES (38,"Full crew", NULL, false);

-- inserts Manufacturer
INSERT INTO AerospaceSector.Manufacturer VALUES (1, "SpaceX", "United States of America", "Elon Musk", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (2, "China National Space Administration (CNSA)", "China", "Zhang Kejian", true);
INSERT INTO AerospaceSector.Manufacturer VALUES (3, "Roscosmos", "USSR of Russia", "Yury Borisov", true);
INSERT INTO AerospaceSector.Manufacturer VALUES (4, "Boeing", "United States of America", "Dave Calhoun", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (5, "United Launch Alliance (ULA)", "United States of America", "Tory Bruno", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (6, "Rocket Lab", "United States of America", "Elon Musk", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (7, "Blue Origin", "United States of America", "Bob Smith", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (8, "Firefly", "United States of America", "Thomas Markusic", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (9, "Virgin Galactic", "United States of America", "Michael Colglazier", false);
INSERT INTO AerospaceSector.Manufacturer VALUES (10, "Relativity space", "United States of America", "Tim Ellis", false);

-- inserts Rockets
INSERT INTO AerospaceSector.Rocket VALUES (1, "Falcon 9B", "active", 67000000, 1);
INSERT INTO AerospaceSector.Rocket VALUES (2, "Falcon Heavy 5B", "active", 130000000, 1);
INSERT INTO AerospaceSector.Rocket VALUES (3, "Starship", "development", 1000000, 1);
INSERT INTO AerospaceSector.Rocket VALUES (4, "Long March 4C", "active", 430000000, 2);
INSERT INTO AerospaceSector.Rocket VALUES (5, "Soyuz", "active", 330000000, 3);
INSERT INTO AerospaceSector.Rocket VALUES (6, "Space Launch System (SLS)", "development", 4000000000, 4);
INSERT INTO AerospaceSector.Rocket VALUES (7, "Delta IV Heavy", "active", 440000000, 5);
INSERT INTO AerospaceSector.Rocket VALUES (8, "Delta IV Medium", "retired", 200000000, 5);
INSERT INTO AerospaceSector.Rocket VALUES (9, "Vulcan", "development", 200000000, 5);
INSERT INTO AerospaceSector.Rocket VALUES (10, "Electron", "active", 7500000, 6);
INSERT INTO AerospaceSector.Rocket VALUES (11, "Neutron", "development", 50000000, 6);
INSERT INTO AerospaceSector.Rocket VALUES (12, "New Shepard", "active", 7500000, 7);
INSERT INTO AerospaceSector.Rocket VALUES (13, "New Glenn", "development", 51000000, 7);
INSERT INTO AerospaceSector.Rocket VALUES (14, "Alpha", "development", 15000000, 8);
INSERT INTO AerospaceSector.Rocket VALUES (15, "SpaceShipTwo", "development", 51000000, 9);
INSERT INTO AerospaceSector.Rocket VALUES (16, "Saturn V", "retired", 185000000, 4);
INSERT INTO AerospaceSector.Rocket VALUES (17, "Terran 1", "development", 12000000, 10);
INSERT INTO AerospaceSector.Rocket VALUES (18, "Terran R", "development", NULL, 10);

-- inserts Launchpads
INSERT INTO AerospaceSector.Launchpad VALUES (1, "KSC SLC-39A", "United States of America", "SpaceX");
INSERT INTO AerospaceSector.Launchpad VALUES (2, "CCSFS SLC-40", "United States of America", "SpaceX");
INSERT INTO AerospaceSector.Launchpad VALUES (3, "VSFB SLC-4E", "United States of America", "SpaceX");
INSERT INTO AerospaceSector.Launchpad VALUES (4, "Boca Chica test sight", "United States of America", "SpaceX");
INSERT INTO AerospaceSector.Launchpad VALUES (5, "xichang B1", "China", "CNSA");
INSERT INTO AerospaceSector.Launchpad VALUES (6, "vostochny Cosmodrome", "Russia", "Roscosmos");
INSERT INTO AerospaceSector.Launchpad VALUES (7, "Kosmodroom Bajkonoer", "Russia", "Roscosmos");
INSERT INTO AerospaceSector.Launchpad VALUES (8, "KSC SLC-39B", "United States of America", "NASA");
INSERT INTO AerospaceSector.Launchpad VALUES (9, "VSFB SLC-6", "United States of America", "ULA");
INSERT INTO AerospaceSector.Launchpad VALUES (10, "CCSFS SLC-37B", "United States of America", "ULA");
INSERT INTO AerospaceSector.Launchpad VALUES (11, "LC-2", "United States of America", "Rocket Lab");
INSERT INTO AerospaceSector.Launchpad VALUES (12, "LC-1", "United States of America", "Rocket Lab");
INSERT INTO AerospaceSector.Launchpad VALUES (13, "Texas LS-1", "United States of America", "Blue Origin");
INSERT INTO AerospaceSector.Launchpad VALUES (14, "VSFB SLC-2", "United States of America", "Firefly");
INSERT INTO AerospaceSector.Launchpad VALUES (15, "Spaceport America", "United States of America", "Virgin Galactic");
INSERT INTO AerospaceSector.Launchpad VALUES (16, "CCSFS SLC-39A", "United States of America", "NASA");
INSERT INTO AerospaceSector.Launchpad VALUES (17, "CCSFS SLC-16", "United States of america", "Relativity Space");

-- insert missions
INSERT INTO AerospaceSector.Mission VALUES (1, "Starlink batch 34", "SpaceX", "2022-01-06", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (2, "ISS crs-20", "NASA", "2020-03-07", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (3, "Demo-2 mission", "NASA", "2020-05-30", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (4, "NRO 108", "NRO", "2020-12-19", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (5, "Crew-2 mission", "NASA", "2021-04-23", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (6, "Starlink batch 26", "Multiple", "2021-05-15", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (7, "SXM-8", "Sirius XM", "2021-06-06", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (8, "USSF III-05", "USSF", "2021-06-17", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (9, "Starlink batch 30", "SpaceX", "2021-09-14", 1, true, 3);
INSERT INTO AerospaceSector.Mission VALUES (10, "Inspiration 4 mission", "Jared Isaacman", "2021-09-16", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (11, "Türksat 5B", "Türksat", "2021-12-19", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (12, "FH4", "USSF", "2022-11-09", 2, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (13, "Kari Danuri", "KARI", "2022-08-04", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (14, "Crew-5 mission", "NASA", "2022-10-06", 1, true, 1);
INSERT INTO AerospaceSector.Mission VALUES (15, "Starlink batch 40", "SpaceX", "2022-10-20", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (16, "Starlink batch 53", "SpaceX", "2023-03-24", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (17, "SDA 23", "SDA", "2023-03-30", 1, true, 3);
INSERT INTO AerospaceSector.Mission VALUES (18, "Starlink batch 60", "SpaceX", "2023-03-30", 1, true, 2);
INSERT INTO AerospaceSector.Mission VALUES (19, "TEMPO mission", "Intelsat & NASA", "2023-04-07", 1, false, 2);
INSERT INTO AerospaceSector.Mission VALUES (20, "Heavy 3", "Various", "2023-04-08", 2, false, 1);
INSERT INTO AerospaceSector.Mission VALUES (21, "Transporter mission", "Various", "2023-04-09", 1, false, 3);
INSERT INTO AerospaceSector.Mission VALUES (22, "Full stack wet rehearsal 1", "Test Static Launch", "2022-03-16", 3, true, 4);
INSERT INTO AerospaceSector.Mission VALUES (23, "Yowgen", "Chinees governement", "2022-03-17", 4, true, 5);
INSERT INTO AerospaceSector.Mission VALUES (24, "MS 21 mission", "Roscosmos/NASA", "2022-03-18", 5, true, 6);
INSERT INTO AerospaceSector.Mission VALUES (25, "MS 22 mission", "Roscosmos/NASA", "2022-09-21", 5, true, 7);
INSERT INTO AerospaceSector.Mission VALUES (26, "MS 23 mission", "Roscosmos/NASA", "2023-02-24", 5, true, 6);
INSERT INTO AerospaceSector.Mission VALUES (27, "Artemis I", "NASA", "2022-11-16", 6, true, 8);
INSERT INTO AerospaceSector.Mission VALUES (28, "NROL-91", "NRO", "2021-09-24", 7, true, 9);
INSERT INTO AerospaceSector.Mission VALUES (29, "NROL-82", "NRO", "2021-04-26", 7, true, 9);
INSERT INTO AerospaceSector.Mission VALUES (30, "GPS III-2", "Boeing", "2020-12-11", 8, true, 10);
INSERT INTO AerospaceSector.Mission VALUES (31, "WGS-9", "NRO", "2017-03-19", 8, true, 10);
INSERT INTO AerospaceSector.Mission VALUES (32, "Stronger Together", "Capella space", "2023-03-16", 10, true, 11);
INSERT INTO AerospaceSector.Mission VALUES (33, "Virginia is for launch lovers", "HawkEye 360", "2023-01-24", 10, true, 11);
INSERT INTO AerospaceSector.Mission VALUES (34, "Catch me if you can", "SNSA", "2022-11-04", 10, true, 12);
INSERT INTO AerospaceSector.Mission VALUES (35, "The beat goes on", "Bluesky", "2023-03-24", 10, true, 12);
INSERT INTO AerospaceSector.Mission VALUES (36, "Test", "Test Launch", NULL, 11, true, NULL);
INSERT INTO AerospaceSector.Mission VALUES (37, "NS-22", "Coby Cotton", "2022-09-12", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (38, "NS-21", "Evan Dick", "2022-06-04", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (39, "NS-20", "Marty Allen", "2022-03-31", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (40, "NS-19", "Michael Strahan", "2021-12-11", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (41, "NS-18", "Audry Powers", "2021-10-13", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (42, "NS-17", "NASA", "2021-08-26", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (43, "NS-16", "Jeff Bezos", "2021-06-20", 12, true, 13);
INSERT INTO AerospaceSector.Mission VALUES (44, "Test", "Test Launch", NULL, 13, true, NULL);
INSERT INTO AerospaceSector.Mission VALUES (45, "Test", "Test Launch", NULL, 9, true, NULL);
INSERT INTO AerospaceSector.Mission VALUES (46, "To the back", "Test Launch", "2022-10-1", 14, true, 14);
INSERT INTO AerospaceSector.Mission VALUES (47, "FLTA001 Dream", "Test Launch", "2021-09-02", 14, true, 14);
INSERT INTO AerospaceSector.Mission VALUES (48, "Victus Nox", "USSF", NULL, 14, false, 14);
INSERT INTO AerospaceSector.Mission VALUES (49, "NASA elana 43", "NASA", NULL, 14, false, 14);
INSERT INTO AerospaceSector.Mission VALUES (50, "Crew 1", "Test Launch", "2021-05-22", 15, true, 15);
INSERT INTO AerospaceSector.Mission VALUES (51, "Crew 2", "Test Launch", "2021-07-21", 15, true, 15);
INSERT INTO AerospaceSector.Mission VALUES (52, "Apollo 11", "NASA", "1969-07-16", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (53, "Apollo 12", "NASA", "1969-11-14", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (54, "Apollo 13", "NASA", "1970-04-11", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (55, "Apollo 14", "NASA", "1971-01-31", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (56, "Apollo 15", "NASA", "1971-07-26", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (57, "Apollo 16", "NASA", "1972-04-16", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (58, "Apollo 17", "NASA", "1972-12-07", 16, true, 16);
INSERT INTO AerospaceSector.Mission VALUES (59, "Good luck, have fun", "Test launch", "2023-03-22", 17, true, 17);

-- insert missionspayload
INSERT INTO AerospaceSector.Missionpayload VALUES (1, 1);
INSERT INTO AerospaceSector.Missionpayload VALUES (2, 2);
INSERT INTO AerospaceSector.Missionpayload VALUES (3, 3);
INSERT INTO AerospaceSector.Missionpayload VALUES (4, 4);
INSERT INTO AerospaceSector.Missionpayload VALUES (5, 5);
INSERT INTO AerospaceSector.Missionpayload VALUES (6, 6);
INSERT INTO AerospaceSector.Missionpayload VALUES (7, 7);
INSERT INTO AerospaceSector.Missionpayload VALUES (8, 8);
INSERT INTO AerospaceSector.Missionpayload VALUES (9, 9);
INSERT INTO AerospaceSector.Missionpayload VALUES (10, 10);
INSERT INTO AerospaceSector.Missionpayload VALUES (11, 11);
INSERT INTO AerospaceSector.Missionpayload VALUES (12, 12);
INSERT INTO AerospaceSector.Missionpayload VALUES (13, 13);
INSERT INTO AerospaceSector.Missionpayload VALUES (14, 14);
INSERT INTO AerospaceSector.Missionpayload VALUES (15, 15);
INSERT INTO AerospaceSector.Missionpayload VALUES (16, 16);
INSERT INTO AerospaceSector.Missionpayload VALUES (17, 17);
INSERT INTO AerospaceSector.Missionpayload VALUES (18, 18);
INSERT INTO AerospaceSector.Missionpayload VALUES (19, 19);
INSERT INTO AerospaceSector.Missionpayload VALUES (20, 20);
INSERT INTO AerospaceSector.Missionpayload VALUES (21, 21);
INSERT INTO AerospaceSector.Missionpayload VALUES (22, 22);
INSERT INTO AerospaceSector.Missionpayload VALUES (23, 23);
INSERT INTO AerospaceSector.Missionpayload VALUES (24, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (25, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (26, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (27, 25);
INSERT INTO AerospaceSector.Missionpayload VALUES (28, 26);
INSERT INTO AerospaceSector.Missionpayload VALUES (29, 27);
INSERT INTO AerospaceSector.Missionpayload VALUES (30, 28);
INSERT INTO AerospaceSector.Missionpayload VALUES (31, 29);
INSERT INTO AerospaceSector.Missionpayload VALUES (32, 30);
INSERT INTO AerospaceSector.Missionpayload VALUES (33, 31);
INSERT INTO AerospaceSector.Missionpayload VALUES (34, 32);
INSERT INTO AerospaceSector.Missionpayload VALUES (35, 33);
INSERT INTO AerospaceSector.Missionpayload VALUES (36, 22);
INSERT INTO AerospaceSector.Missionpayload VALUES (37, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (38, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (39, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (40, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (41, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (42, 34);
INSERT INTO AerospaceSector.Missionpayload VALUES (43, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (44, 22);
INSERT INTO AerospaceSector.Missionpayload VALUES (45, 22);
INSERT INTO AerospaceSector.Missionpayload VALUES (46, 22);
INSERT INTO AerospaceSector.Missionpayload VALUES (47, 22);
INSERT INTO AerospaceSector.Missionpayload VALUES (48, 35);
INSERT INTO AerospaceSector.Missionpayload VALUES (49, 36);
INSERT INTO AerospaceSector.Missionpayload VALUES (50, 37);
INSERT INTO AerospaceSector.Missionpayload VALUES (51, 38);
INSERT INTO AerospaceSector.Missionpayload VALUES (52, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (53, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (54, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (55, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (56, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (57, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (58, 24);
INSERT INTO AerospaceSector.Missionpayload VALUES (59, 22);


